### ISSUE TITLE
MQTT IP address 

### ISSUE THREAD

**Issue by TonyFrend** [uptoratlen/tpLinkM4Reboot#5]
Please advise where I can find the MQTT IP address for my implementation. 

Is this the IP address of the server that the cron job is running on?

Many thanks,

Tony

**Comment by uptoratlen** [comment]
Hi,
You need a MQTT Server. See eg. https://en.wikipedia.org/wiki/MQTT
So the answer is: In case you do not know the IP of the MQTT, you ain't got one. 
The idea is or was (as I do not use TpLink anymore), that the script sends to the MQTT Server a message on a certain topic and so, e.G. a followed NodeRed Server was able to : show a message on a Homeautomation like Domoticz.
Now you got even more confused I guess.
Let's say: script --> MQTT --> NODERED --> DOMOTICZ  (here a small widget shows the last statu so dthe script).
SOund complicated? Yes and no, as all other parts pre-existed before the TpLink Reboot.
Maybe you like a eg. small mail notification? Maybe someone forks it and adds it. As said, I do not use TpLink anymore.

**Comment by TonyFrend** [comment]
Hi, That explains things :). Managed to get a mqtt server installed and running on my QNAP NAS server which eliminated the mqtt error. Now working through the rest of the error messages one by one.

The next challenge seems to be getting Firefox running on my QNAP server.

Error messages:

/root/tplink/tpLinkM9Reboot.py:61: DeprecationWarning: firefox_profile has been deprecated, please use an Options object
  profile = webdriver.FirefoxProfile()
/root/tplink/tpLinkM9Reboot.py:62: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object
  driver = webdriver.Firefox(options=options, firefox_profile=profile, executable_path='geckodriver')
Traceback (most recent call last):
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/tplink/tpLinkM9Reboot.py", line 62, in <module>
    driver = webdriver.Firefox(options=options, firefox_profile=profile, executable_path='geckodriver')
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 172, in __init__
    self.service.start()
  File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.


Thanks for your help.

**Comment by acc4ever** [comment]
> Hi, That explains things :). Managed to get a mqtt server installed and running on my QNAP NAS server which eliminated the mqtt error. Now working through the rest of the error messages one by one.
> 
> The next challenge seems to be getting Firefox running on my QNAP server.
> 
> Error messages:
> 
> /root/tplink/tpLinkM9Reboot.py:61: DeprecationWarning: firefox_profile has been deprecated, please use an Options object profile = webdriver.FirefoxProfile() /root/tplink/tpLinkM9Reboot.py:62: DeprecationWarning: firefox_profile has been deprecated, please pass in an Options object driver = webdriver.Firefox(options=options, firefox_profile=profile, executable_path='geckodriver') Traceback (most recent call last): File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 71, in start self.process = subprocess.Popen(cmd, env=self.env, File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/subprocess.py", line 966, in **init** self._execute_child(args, executable, preexec_fn, close_fds, File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/subprocess.py", line 1842, in _execute_child raise child_exception_type(errno_num, err_msg, err_filename) FileNotFoundError: [Errno 2] No such file or directory: 'geckodriver'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/root/tplink/tpLinkM9Reboot.py", line 62, in driver = webdriver.Firefox(options=options, firefox_profile=profile, executable_path='geckodriver') File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/site-packages/selenium/webdriver/firefox/webdriver.py", line 172, in **init** self.service.start() File "/share/CACHEDEV1_DATA/.qpkg/Python3/python3/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 81, in start raise WebDriverException( selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
> 
> Thanks for your help.

I had the same issue, I solved it installing selenium v3 with this code ....
pip3 install 'selenium<4.0.0'

Maybe [uptoratlen] can update the install instruccion, hope it works for you...

**Comment by uptoratlen** [comment]
Your wish is my command :-)
Nice that this is still working for you. Sad that TP Link did not ever added such a feature.
